### ISSUE TITLE
isPromise should test for other categories of thennable 

### ISSUE THREAD

**Issue by henrymazza** [DockYard/ember-composable-helpers#102]
Currently utils module `isPromise` tests only for `instanceof` Promise, however in Ember the occurrence of PromiseProxy Mixin is far more comum. I can't recall right now, but may be other types of thennable objects besides those two, so perhaps isPromise should be chnged to isThennable? Ideas?

**Comment by poteto** [comment]
Give `0.17.1` a try and let me know if you still have the same issue.

**Comment by henrymazza** [comment]
This is new to me: `typeOf(obj) === 'object'` evaluates to false because `typeOf(obj)` returns `"instance"` instead of the expected `"object"~.

**Comment by poteto** [comment]
😑 I'll fix it later when I land, my flight is about to take off

**Comment by henrymazza** [comment]
Ah! Got it. `typeOf()` is Ember's own implementation of `typeof`. tsc tsc tsc

No problem. Have a nice trip!

**Comment by poteto** [comment]
Haha yeah we got trolled by this before

**Comment by poteto** [comment]
My plane has wifi :D it should be finally fixed now

**Comment by henrymazza** [comment]
Great work! Have a nice weekend! :beers:


On 5 de março de 2016 at 17:46:47, Lauren Tan (notifications@github.com) wrote:

My plane has wifi :D it should be finally fixed now
