### ISSUE TITLE
group-by breaks with async relationships

### ISSUE THREAD

**Issue by Asherlc** [DockYard/ember-composable-helpers#109]
`group-by` assigns and retrieves everything internally using get/set, so it can't handle a group by property  that returns anything other than a string. This means you can't group by a relationship, or by even a string property of a relationship (since it'll initially return `undefined` before the relationship loads).

**Comment by Asherlc** [comment]
Contrast it with this `groupBy` implementation which appears would work: https://github.com/HeroicEric/ember-group-by/blob/master/addon/macros/group-by.js

**Comment by Asherlc** [comment]
Here's a combo I put together, it works asynchronously. It's a bit different in that it returns an object like so: `{ <grouped property name>: <grouped property value>, items: <grouped items> }`

https://gist.github.com/Asherlc/cc438c9dc13912618b8b

**Comment by henrymazza** [comment]
:+1:

**Comment by ludalex** [comment]
👍 +1

**Comment by martndemus** [comment]
We wont fix this particular issue, please use another addon that implements it the way you requested it.
