### ISSUE TITLE
EncodeURI helper

### ISSUE THREAD

**Issue by Panman8201** [DockYard/ember-composable-helpers#110]
I've created an `{{encode-uri}}` helper which might fit well here. My use case is for `mailto:` links where I wanted to include a property as the `subject` within the link. It basically wraps the ES3 [`encodeUri()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) and [`encodeUriComponent()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent). Below is all it is, I could create a PR with tests if accepted.

```javascript
import Ember from 'ember';

export function encodeUri(params, hash) {
  const component = hash.component || false;
  const separator = hash.separator || '';
  const joinedParams = params.join( separator );
  return (component ? encodeURIComponent( joinedParams ) : encodeURI( joinedParams ) );
}

export default Ember.Helper.helper(encodeUri);
```

Usage:

```hbs
{{encode-uri "abc"}}
{{encode-uri "xyz" component=true}}
{{encode-uri "abc" "xyz" separator=","}}
```

**Comment by martndemus** [comment]
I think this one is useful enough to warrant it's own add-on.
Thoughts @poteto?

**Comment by poteto** [comment]
Agreed, I also think this is useful and should likely be its own addon... 

`ember-composable-helper` in my mind is a generic utility library for dealing with UI and presentational logic, with helpers that are _composable_ with one another. I'm not sure how this one will fit in with the others

**Comment by Panman8201** [comment]
Fair enough, do you know of another addon for those types of helpers? Seems like a bit of overkill to have an addon for one, small helper. ¯\_(ツ)_/¯

**Comment by poteto** [comment]
Not at all! I had an addon for just the `toggle` helper, although that has been moved here. Perhaps you could make a Helper library for dealing with URIs in general? For example, I know it's a common ask for a helper that translates a route's path into a URL. 

```hbs
{{route-to-url "posts.show" 1}} {{! http://www.example.com/posts/show/1 }}
```

**Comment by Panman8201** [comment]
@poteto [ember-href-to](https://www.npmjs.com/package/ember-href-to) :wink: And I thought I had seen that proposed to be included into Ember, and a "is-route-active" type helper. I'll keep this one on my TODO list.
