### ISSUE TITLE
Add a development blueprint for class based helpers.

### ISSUE THREAD

**Issue by martndemus** [DockYard/ember-composable-helpers#114]
Should generate something like:

```js
import Ember from 'ember';

const {
  Helper,
  computed,
  observer,
  get,
} = Ember;

export default Helper.extend({
  compute(/* params, hash */) {
    return get(this, 'content');
  },

  content: computed(/* props, */ function() {

  }),

  contentDidChange: observer('content', function() {
    this.recompute();
  })
});
``

**Comment by poteto** [comment]
As part of this blueprint, we should also mandate that the actual helper logic should live as an exported function (see https://github.com/dockyard/ember-composable-helpers/blob/master/addon%2Fhelpers%2Fcontains.js) for an example. This would let the consuming app import the logic itself if desired.

**Comment by poteto** [comment]
The `content` CP should have the `readOnly` extension as well.
