### ISSUE TITLE
Expected `inc` to work as an action

### ISSUE THREAD

**Issue by samselikoff** [DockYard/ember-composable-helpers#126]
(Amaaazing addon, thanks for this)

I was working with this addon this morning tried something like

```
{{input focus-out=(action (inc hasBlurred)) }}
```

1. I realize now that `inc` is not listed under Actions, but at the time I spent a while debugging trying to get it to work. I wonder if the docs should split the helpers into two sets, ones that work with actions and ones that don't?
2. Conceptually is there a reason it can't work with actions, or do we just need to update it?
3. [The docs](https://github.com/DockYard/ember-composable-helpers#inc) show mutating a property on the context, but I don't think that works. It's not covered in the test suite + I added a test for this that fails. Want me to PR this test + update `inc` so it works on properties?
4. What do you think of a `{{set}}` helper? Basically, I just wanted a way to set a `boolean` to true, something like

```
{{input focus-out=(action (set hasBlurred true)) }}
```

**Comment by martndemus** [comment]
I think @rwjblue mentioned that 1 is possible, we should research it.

I don't think the example you mention in 3 is mutating on the context. It might just lack some template context.

For 4 you can just do:
```hbs
{{input focus-out=(action (mut hasBlurred) true) }}
```

**Comment by samselikoff** [comment]
Ohhh right. mut. der.

**Comment by martndemus** [comment]
Closing, see #91 for rationale.

**Comment by samselikoff** [comment]
Thanks for pointing to the discussion, makes sense to me.
