### ISSUE TITLE
Contains helper

### ISSUE THREAD

**Issue by poteto** [DockYard/ember-composable-helpers#13]
Contains single item:

```js
contains([foo, bar, baz], baz) === true;
```

```hbs
{{if (contains cart selectedItem) "Remove from cart" "Add to cart"}}
```

Contains all items:

```js
contains([foo, bar, baz], [foo, bar]) === true;
contains([foo, bar, baz], [foo, qux]) === false;
contains([foo, bar, baz], [foo, bar, baz]) === true;
contains([foo, bar, baz], [foo, bar, baz, qux]) === false;
```
```hbs
{{if (contains cart selectedItems) "Remove all from cart" "Add all to cart"}}
```

**Comment by poteto** [comment]
Also consider `includes` as a name for the helper – https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

**Comment by jevanlingen** [comment]
> Also consider includes as a name for the helper – https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

As the Ember Enumerable contains is [deprecated](https://www.emberjs.com/deprecations/v2.x/#toc_enumerable-contains) for a while now, this helper should definitely be renamed to `includes`!
