### ISSUE TITLE
group-by adds extra 'toString' group

### ISSUE THREAD

**Issue by Padchi** [DockYard/ember-composable-helpers#136]
This simple thing (one comment only) `{{log (group-by "id" post.comments)}}` gives 2 groups. One with the ID and one called `toString`.
![skarmavbild 2016-04-18 kl 19 11 34](https://cloud.githubusercontent.com/assets/814347/14612797/64fe11e6-0599-11e6-9f9c-56bee19b8c10.png)

Using Ember 2.5.0 and the latest ember-composable-helpers.

**Comment by martndemus** [comment]
This is a bug in Ember, see emberjs/ember.js#13050

**Comment by ivanvotti** [comment]
@martndemus Can the `group-by` helper remove the `toString` group somehow, until the Ember's bug is fixed? Anyway, the `toString` stuff should be mentioned in the `README`.

At this moment I have to use this ugly workaround: `{{if (not-eq groupName 'toString') groupName}}`

**Comment by ivanvotti** [comment]
Looks like the bug is fixed in [Ember 2.5.1](https://github.com/emberjs/ember.js/releases/tag/v2.5.1).
At least I don't see it anymore on my side after the upgrade.

**Comment by Padchi** [comment]
Yes, https://github.com/emberjs/ember.js/releases/tag/v2.5.1?utm_source=Ember+Weekly&utm_campaign=650333acdb-Ember_Weekly_Issue_156&utm_medium=email&utm_term=0_e96229d21d-650333acdb-95297733

Skickat från min iPhone
