### ISSUE TITLE
Set helper

### ISSUE THREAD

**Issue by poteto** [DockYard/ember-composable-helpers#139]
Sugar for `(action (mut name) value)`. Helpful when using it in a pipe

**Comment by poteto** [comment]
Not sure how useful this would be, it's not much of a win over using `action (mut someValue)`:

```hbs
<button onclick={{action (pipe (action "shouldToggle") (set "someValue" this) thing}}>Blah</button>
<button onclick={{action (pipe (action "shouldToggle") (action (mut someValue)) thing}}>Blah</button>
```

**Comment by samselikoff** [comment]
I like it, feels like it's more descriptive when what you want to do is just "set". Bummer you have to include `this` though.

**Comment by poteto** [comment]
Yeah, unless we use private APIs, we would have to pass in the object to set the value on, which isn't much of a win to me. Would be nice if `mut` worked as an action without having to wrap it in one
