### ISSUE TITLE
(array ) helper maybe?

### ISSUE THREAD

**Issue by taras** [DockYard/ember-composable-helpers#142]
Sometimes it's helpful to compose an array in the template. 

What do you think about something like this?

```hbs
{{#each (array 'foo' 'bar' 'baz') as |word|}}
  {{word}}
{{/each}}
```

The implementation is like hash helper,

```javascript
export default Ember.Helper.helper(function(params) {
  return params;
});
```

If you agree, I'll make a PR. 

Also, if there is another way to do with that's already built-in, please let me know!

**Comment by martndemus** [comment]
It might not be obvious from the readme (sorry) but the `append` helper will do this for you!

**Comment by martndemus** [comment]
Although it will try to join arrays together. So maybe it is better to have the array helper.
Thoughts @poteto?

**Comment by poteto** [comment]
Could be a nice sister helper to `hash`, I'm all for it!

**Comment by taras** [comment]
cool 👍

**Comment by taras** [comment]
@zigahertz just submitted the PR with array helper but we found some unexpected behaviour.

In JavaScript, empty arrays evaluate to true. It seems that in HTMLBars, empty arrays evaluate to false. We added a test to that effect. I'm not sure if this is an issue, but I wanted to bring this to your attention.
