### ISSUE TITLE
chunk helper does not respect computed length properties

### ISSUE THREAD

**Issue by blimmer** [DockYard/ember-composable-helpers#147]
When passing the result of `Store.peekAll` (a `RecordArray`), length is a computed property. The chunk helper does not `get` the computed property and throws an exception.

[Here](https://github.com/DockYard/ember-composable-helpers/blob/master/addon/helpers/chunk.js#L13) we don't `.get` the length from the array, which causes the length var to be assigned to a CP. Then, [this line](https://github.com/DockYard/ember-composable-helpers/blob/master/addon/helpers/chunk.js#L20) throws an exception since length isn't an int:

```
chunk.js:45 Uncaught RangeError: Invalid array length
```

**Comment by martndemus** [comment]
Good catch! Could you conjure up a PR that fixes this for us?

**Comment by blimmer** [comment]
Do you have any recommendation on how to write a test for this? 

Currently there's no ember-data dependency in this add on, so testing with a RecordArray currently doesn't seem right. 

Ember.Array proxies on the prototype to get the length. 

I was thinking I could mock this out or pull in ember data. Do you have a preference on how I do that?

**Comment by martndemus** [comment]
You could use `ArrayProxy` to mock a `RecordArray`. See http://emberjs.com/api/classes/Ember.ArrayProxy.html#property_length

**Comment by blimmer** [comment]
Nice. Thank you for the tip. I'll try to whip up a PR.
