### ISSUE TITLE
Will this addon work on Ember versions 1.13.x?

### ISSUE THREAD

**Issue by somasuna** [DockYard/ember-composable-helpers#153]

**Comment by martndemus** [comment]
Yes

**Comment by somasuna** [comment]
I'm trying to use this addon with `ember v1.13.5, ember-shims v0.0.6 and ember-data with 1.0.0-beta.16.1`. But this addon requires ember-shims version 0.1.1- which doesn't have Ember-Data in bower dependency.  
So when i try to use with ember-shims version 0.1.1, I am getting an error as module ember-data not available. Could you please help me on this?

**Comment by HeroicEric** [comment]
@somasuna you don't actually need that version of ember-shims. You should be OK with v0.0.6

**Comment by somasuna** [comment]
In bower dependency the ember-shims version mentioned is 0.1.1. So it is forcing me to install that version(0.1.1) only.
