### ISSUE TITLE
array helper not updating to bound properties

### ISSUE THREAD

**Issue by SirZach** [DockYard/ember-composable-helpers#154]
I'm trying to do something like this:

``` handlebars
{{my-component classNames=(array 'row' (if someProp 'bound' 'unbound'))}}
```

The first time `array` calculates it does so correctly with the `if` helper but when the value of `someProp` changes, the `array` helper doesn't update.

**Comment by taras** [comment]
@SirZach can you please create a failing test because this should work

**Comment by BryanCrotaz** [comment]
We're seeing the same problem in `find-by` with a nested helper in Ember 2.13.3 - we weren't seeing this in older Ember

**Comment by snewcomer** [comment]
IN glimmer if the argument changes, the helper is re-ran!
