### ISSUE TITLE
Suppressing output of a subexpression

### ISSUE THREAD

**Issue by taras** [DockYard/ember-composable-helpers#155]
In a library that @zigahertz are working on, we're using a helper that prevents output of a helper from being rendered. This is useful for us to make it possible to execute pipes on render and consequently on rerender. 

We've been calling it `dev-null` and all it does is this:

```js
export default Ember.Helper.helper(function(){
});
``` 

If you think this is useful, then we'll create a PR otherwise we'll release it as a separate addon.

What do you think?

**Comment by martndemus** [comment]
This smells like your helper gets recomputed too often, can you share a code sample of when you'd want to use this?

**Comment by taras** [comment]
@martndemus I don't think it'd be recomputed more often than a usual helper. I should add that it's useful as a helper more than a sub-expression. 

For example,

```
{{dev-null (pipe (action 'foo') (action 'returnsPromise'))}}
```

This would execute the pipe, but the result would be swallowed. It'd only recompute when the parameters change.

**Comment by martndemus** [comment]
Looks like you have implemented this in https://github.com/EmberSherpa/ember-reactive-helpers.
Closing this issue.

**Comment by taras** [comment]
Yah, I did. Thanks
