### ISSUE TITLE
"WARNING: Dependent keys containing @each only work one level deep" when nesting array helpers

### ISSUE THREAD

**Issue by gossi** [DockYard/ember-composable-helpers#177]
Hey guys,

I recently updated to ember `2.6.0` (ember and ember-data). Now I'm getting this warning:

> WARNING: Dependent keys containing @each only work one level deep. You cannot use nested forms like todos.@each.owner.name or todos.@each.owner.@each.name. Please create an intermediary computed property.

My relevant code for this:
```
{{#skill-list skills=(reject-by "multipleOf.name" (reject-by "variationOf.name" model.skills)) as |skill|}}
	{{skill-list-item skill=skill}}
{{/skill-list}}
```

Seems like to happen, when nesting multiple of the composable array helpers.

ember-composable-helpers: `0.26.2`

**Comment by martndemus** [comment]
Yes, this is a limitation of Ember.js, nothing we can do about.

**Comment by rmachielse** [comment]
@martndemus I am seeing a lot of those errors as well. I think it is possible to prevent those errors.

When using this:
```handlebars
{{log (filter-by 'relation.id', 1 models)}}
```

The composable helper will do this:
```javascript
filtered: computed('models.@each.relation.id', function() {
  return this.get('models').filterBy('relation.id', 1);
})
```

However the error won't occur if it would do this:
```javascript
filtered: computed('models.@each.relation', function() {
  return this.get('models').filterBy('relation.id', 1);
})
```

(the `.id` part is chopped from the byPath.)

For example if [this line](https://github.com/DockYard/ember-composable-helpers/blob/master/addon/helpers/filter-by.js#L47) would be changed to this:

```javascript
let [minimumByPath] = byPath.split('.');
let cp = filter(`array.@each.${minimumByPath}`, filterFn);
```

the behaviour would be the same but without the warning.

What do you think?

**Comment by ludalex** [comment]
@rmachielse that small change works perfectly for me and removes the warning. I used it for my specific use case which is the `group-by` helper. I think it could be applied to all filtering/grouping helpers.

Why don't you propose a pull request?

**Comment by rmachielse** [comment]
@ludalex yeah I was thinking about that, but I would like some feedback from the maintainers. @poteto @martndemus what do you think?

**Comment by Gorzas** [comment]
I've got the same warning and I think that the solution of @rmachielse could be a great fix. Could we reopen this issue?

**Comment by pkmh** [comment]
@Gorzas are you planning on putting out a PR with your fix to filter-by?

**Comment by Gorzas** [comment]
@pkmh Done! :smile:
