### ISSUE TITLE
transitionTo action

### ISSUE THREAD

**Issue by deepflame** [DockYard/ember-composable-helpers#183]
Hi there!

I find myself very often just writing a `route-action` to transition to a different route.
So I would find it useful to have an action just for that like:

```
{{my-component onClick=(transition-to "next.route" model)}}
```

it would also be possible to combine it with the pipe or similar. So when the pipe it finished it could transition to a different route.

Any thoughts on this?

**Comment by taras** [comment]
@deepflame I have this helper in `ember-reactive-helpers` https://github.com/EmberSherpa/ember-reactive-helpers#transition-to-destination-model-query-params-foobar

**Comment by taras** [comment]
@martndemus @poteto do you want this helper in `ember-composable-helpers` - it doesn't fit very well with the reactive helpers. If you're interested in this helper, I can deprecate it from my library and create a PR here.

**Comment by poteto** [comment]
I'm a little bit hesitant about this helper, it doesn't really add any new template functionality. But since there is a config to include/exclude helper I think I would be open to it

**Comment by taras** [comment]
@poteto alternatively, we could create a routing helpers addon. On the last Ember Show, @ef4 talked about wanting to create routing helpers for all common functionality of `link-to`. We could create a bucket component that'll have all of those helpers in there. 

What do you think?

**Comment by martndemus** [comment]
@taras you should probably coordinate with the `href-to` people.

**Comment by taras** [comment]
@martndemus yeah, i was thinking the same thing. I'll reach out to @gavinjoyce about it.

**Comment by deepflame** [comment]
Thanks a lot for your initiative @taras . Highly appreciated! :)

**Comment by martndemus** [comment]
Closing this for now, I'll reopen if further discussion is needed here.
