### ISSUE TITLE
`(map` helper

### ISSUE THREAD

**Issue by taras** [DockYard/ember-composable-helpers#184]
This addon has `map-by` but not map. Map could receive a function and apply it to the array. 

It would have the same arguments order as `map-by` but accept a callback instead of key.
```hbs
{{#each (map callback array) as |item|}}
  {{item.title}}
{{/each}}
```

What do you think? Would you accept a PR with this if one was created?

**Comment by martndemus** [comment]
@taras yes, would you also be willing to do the same for `filter` and maybe `reduce`? Also see `filter-by` for an example where an action is used as loop function.

**Comment by poteto** [comment]
Agreed

**Comment by taras** [comment]
Here is a PR for this #185
