### ISSUE TITLE
Array manipulation helpers

### ISSUE THREAD

**Issue by taras** [DockYard/ember-composable-helpers#186]
Would you accept helpers for manipulating arrays?

For example, take an array and add a few items to it.

```hbs
{{#each (push-object (hash name='red') colors) as |color|}}
  {{color.name}}
{{/each}}
```

This helper would use Ember's `Array.pushObject` to push object into the array.

Same helpers could be created for `push-objects`, `remove-object` and `remove-objects`.

Let me know if you'd accept a PR and I'll put one together.

**Comment by martndemus** [comment]
Not really, helpers should not mutate their input. It would be okay if it returned a copy and then did that operation. It could also return an action that would do that operation.

**Comment by taras** [comment]
@martndemus I agree that helpers shouldn't mutate their input but this won't work with Ember Data Model instances - AFAIK. 

I like the idea of returning an action that'll perform this operation but it'll be confusing because `Array.pushObject` doesn't behave this way. It might be reasonable to say that `push-object` mutates the array that you pass into it because that's how Ember's `Array.pushObject` behaves. 

After all, `Array.pushObject` is a prototype function that Ember adds to allow arrays to be observable. It seems in order that they'll do the same in template (even though it's the most convenient behaviour)

What do you think?

**Comment by poteto** [comment]
Anything with a side effect should be an action IMO. The problem is `(push-object (hash name='red') colors)` will effectively push `red` into the `colors` array every time it is invoked. It is no longer a presentational helper, and will likely lead to a lot of self-trolling. As a side note, we already have the `append` helper which does the same thing but returns a new array https://github.com/DockYard/ember-composable-helpers#append

**Comment by taras** [comment]
@poteto I see what you mean now. Returning an action allows to apply a change triggered by an event. `append` helper will probably suffice for what I need. I forgot about it. Thank you for entertaining my question. I'll close this now.
