### ISSUE TITLE
Inconsistent checks for arrays

### ISSUE THREAD

**Issue by jondayton** [DockYard/ember-composable-helpers#197]
In checking to see if the object is an array

`contains` uses `typeOf(haystack) !== 'array')`
`invokes` uses `isEmberArray(obj)`

This can lead to inconsistencies in using Ember arrays in templates.

**Comment by martndemus** [comment]
Would you be willing to shoot a PR that updates all cases to `isEmberArray`?

**Comment by jondayton** [comment]
Yes I'll do that.

**Comment by martndemus** [comment]
You're awesome! :+1:

**Comment by jondayton** [comment]
I'm noticing there's also `{ isEmberArray as isArray }`

is the preferred syntax `isEmberArray(array)` or `isArray(array)`?

**Comment by martndemus** [comment]
It should all be `isEmberArray`.
