### ISSUE TITLE
bug: repeat helper fails integration tests

### ISSUE THREAD

**Issue by dfalling** [DockYard/ember-composable-helpers#217]
## Version
1.0.0

## Test Case
```
{{#each (repeat data.depth) as |empty|}}
  &nbsp;&nbsp; 
{{/each}}
```

## Steps to reproduce
1) Create an integration test using the above snippet
```
this.set('data', { depth: 2 });
this.render(hbs`{{repeat-test data=data}}`);
```
2) Run the test with the `ember test` command

## Expected Behavior
The test should succeed.

## Actual Behavior
The test fails:
>
    ---
        message: >
            '[object Object]' is not a valid argument for 'Function.prototype.apply' (evaluating 'Array.apply')
        stack: >
            TypeError: '[object Object]' is not a valid argument for 'Function.prototype.apply' (evaluating 'Array.apply')
                at repeat (http://localhost:7357/assets/vendor.js:104708)

**Comment by martndemus** [comment]
I added te following test to the test-suite:
```js
test('Repeat fail', function(assert) {
  this.registry.register('template:repeat-test', hbs`
    {{#each (repeat data.depth)  as |empty|}}
      &nbsp;&nbsp;
    {{/each}}
  `);

  this.set('data', { depth: 2 });
  this.render(hbs`{{repeat-test data=data`);
});
```

It did not fail when running the tests agains master.
