### ISSUE TITLE
Helper performance improvements

### ISSUE THREAD

**Issue by aaronbhansen** [DockYard/ember-composable-helpers#224]
I was stepping through the helpers yesterday and noticed many of them doing extra computations that could be avoided. The use of observers aren't needed in many of the helpers today. For this example, lets take the filter-by helper.

**One method**
compute

**Two observers**
byPathDidchange, contentDidChange

Calling the helper, currently the following execution chain happens.

```
(filter-by "property" "value" array)
```

Compute is called on the helper
- on line 20 byPath is set.
- Since observers are synchronous, byPathDidChange is executed. 1st time.
- on line 21 value is set.
- byPathDidChange is executed again for 2nd property change. 2nd time called.

A property is defined twice that only needs to be defined once. 

If at any point any of the parameters passed in is changed, the helper will be called again and compute is executed. 

By its nature, the observer byPathDidChange is never called because the parameters its observing can't change unless compute is called. Compute is called anytime a parameter changes, so no need to observe on those properties. 

contentDidChange is still needed, but any other observers could be removed. 

Proposed solution. 
1. Remove as many observers as possible. They aren't needed and are extra work being done
2. Change byPathDidChange to a method -> initializeProperty and call that from compute.
3. Don't set any extra properties to helper than needed. The only real property needing to be set is array, the others can be passed in an used within the initializeProperty scope. 

Possible solution

```
import Ember from 'ember';
import { isEmberArray } from 'ember-array/utils';
import { filter } from 'ember-computed';
import Helper from 'ember-helper';
import get from 'ember-metal/get';
import observer from 'ember-metal/observer';
import set from 'ember-metal/set';
import { isEmpty, isPresent } from 'ember-utils';

const { defineProperty } = Ember;

export default Helper.extend({
  compute([byPath, value, array]) {
    if (!isEmberArray(array) && isEmberArray(value)) {
      array = value;
      value = undefined;
    }

    set(this, 'array', array);
    this.initializeProperty(byValue, value);

    return get(this, 'content');
  },

  initializeProperty(byPath, value) {
    if (isEmpty(byPath)) {
      defineProperty(this, 'content', []);
      return;
    }

    let filterFn;

    if (isPresent(value)) {
      if (typeof value === 'function') {
        filterFn = (item) => value(get(item, byPath));
      } else {
        filterFn = (item) => get(item, byPath) === value;
      }
    } else {
      filterFn = (item) => isPresent(get(item, byPath));
    }

    let cp = filter(`array.@each.${byPath}`, filterFn);

    defineProperty(this, 'content', cp);
  },

  contentDidChange: observer('content', function() {
    this.recompute();
  })
});
```

**Comment by snewcomer** [comment]
I think we can start looking at alternate solutions now.  Ref #319
