### ISSUE TITLE
Group-by not triggering async call to fetch relationships

### ISSUE THREAD

**Issue by jamesdixon** [DockYard/ember-composable-helpers#228]
## Version
1.1.2 (saw in 1.0.0 as well)

## Test Case
https://ember-twiddle.com/1813ede49e9bb2cae13d75fc9ad44298?openFiles=templates.index.hbs%2C

## Steps to reproduce
When you load the Twiddle, you'll notice that a network request goes out to fetch line items 1 & 2 (fails because it's a twiddle). This is a result of attempting to loop over the model's `lineItems` relation, without the records having been loaded.

If you comment out the `each` loop and then uncomment the `group-by` component, you'll see that it throws the following error: `Error: Assertion Failed: The key provided to get must be a string, you passed undefined`.

## Expected Behavior
I'd expect that the relations would be asynchronously loaded as they are when using `model.lineItems` in the `{{#each...}}` component.

## Actual Behavior
This error is thrown: ``Error: Assertion Failed: The key provided to get must be a string, you passed undefined`.`

**Comment by jamesdixon** [comment]
Note that no error is thrown if the relations already exist in the store.

**Comment by frank06** [comment]
James, both are doing a similar kind of `forEach` and none is waiting for the promise (`DS.PromiseManyArray` proxy) to resolve.

The difference is that `group-by` *needs* to `get` a specific property value of the models, the one you are grouping by: `name`.

An option to fix this is wrapping the `group-by` with `await` ([ember-promise-helpers](https://github.com/fivetanley/ember-promise-helpers)). The stateful `await` helper will automatically recompute and return the resolved promise, the `if` receives that non-null value and yields the block.

Inside the block, `model.lineItems` is now resolved so `group-by` can now access the `name` property in all objects in the array.

```handlebars
{{#if (await model.lineItems) }}
  {{#each-in (group-by "name" model.lineItems) as |name lineItems|}}
    <h1>{{name}} Artists</h1>
  
    <ul>
      {{#each lineItems as |item|}}
        <li>{{item.name}}</li>
      {{/each}}
    </ul>
  {{/each-in}}
{{/if}}
```

Hope that makes sense.

**Comment by jamesdixon** [comment]
@frank06 that worked beautifully! Appreciate the education. I should hire you!
