### ISSUE TITLE
The next helper ({{has-next}}, {{next}} array helpers)

### ISSUE THREAD

**Issue by xamoom-pali** [DockYard/ember-composable-helpers#229]
## Version

version 1.1.2 (tried out with older versions and faced the same problem)
## Test Case

Giving the **{{has-next}}** or **{{has-previous}}** helpers an array of Ember objects, the result will always be `false` although the next item is found. 

```
//js
const firstItem = Ember.Object.create({id: 'first'});
const secondItem = Ember.Object.create({id: 'second'});
const collection = Ember.A([ firstItem, secondItem ]);

this.set('firstItem', firstItem);
this.set('secondItem', secondItem);
this.set('collection', collection);

//hbs
{{! always false }}
{{has-previous secondItem true collection}}
{{has-next firstItem true collection}}  
```

It seems to me that the [previous helper](https://github.com/DockYard/ember-composable-helpers/blob/master/addon/helpers/previous.js#L14) and [next helper](https://github.com/DockYard/ember-composable-helpers/blob/master/addon/helpers/next.js#L15) have same source of the problem:
`return currentIndex === lastIndex ? currentValue : array[currentIndex + 1];`

Since `array` is an Ember array, it does not return its item using curly brackets `[]` syntax.

Trying out the following just to clarify my assumption fixed the problem:

`return currentIndex === lastIndex ? currentValue : (array[currentIndex + 1] || array.objectAt(currentIndex+1));`
## Expected Behavior

{{has-previous}} / {{has-next}} helper should return true if given array is an Ember array and the next helper finds a ,predecessor' / ,successor'.
## Actual Behavior

{{has-previous}} / {{has-next}} helper returns false although the next item in given array is found.
## Note

I stumbled upon the problem using the {{next}}/{{previous}} helpers.

**Comment by nruth** [comment]
I think you're on to something. I was able to use the hint that "Since array is an Ember array, it does not return its item using curly brackets [] syntax." to change my code from

`{{#if (has-next question (get question 'mockPaper.questions'))}}`

to 

`{{#if (has-next question (flatten (get question 'mockPaper.questions')))}}`

using flatten to create a new array from whatever object the relationship returns instead of an array, and all of a sudden I get the expected next/previous button behaviour.

I'm on Ember-CLI 2.8 defaults + composable helpers 1.1.2.

**Comment by gmurphey** [comment]
I wasn't able to reproduce this with 1.1.2:
https://ember-twiddle.com/7f26adf45254d0c36536c248a25676ba?fileTreeShown=false&openFiles=templates.application.hbs%2C

Also wrote some tests around this and those also pass: https://github.com/gmurphey/ember-composable-helpers/commit/1c5d34958fbaa83c0b70f58acfe82f0af89d4cc3

**Comment by xamoom-pali** [comment]
The collection is a hasMany relationship, I made a screenshot pointing out arguments passed to the helper.
![debug_screenshot](https://cloud.githubusercontent.com/assets/11027796/20341696/94a10f62-abe7-11e6-83bd-726ac733b990.png)

**Comment by jamesdixon** [comment]
@gmurphey I can confirm @xamoom-pali's findings. I'm running 1.1.2 on Ember 2.9 and ran into the same situation. Using the solution above resolved my issue.

**Comment by jamesdixon** [comment]
Thanks @xamoom-pali !
