### ISSUE TITLE
`fmt` string helper

### ISSUE THREAD

**Issue by nucleartide** [DockYard/ember-composable-helpers#245]
Hiya,

Earlier today I was refactoring computed properties into helpers, and I thought it might be slightly easier to have a `fmt` helper, instead of the standard `concat` helper that comes with Ember.

`concat` example:

```hbs
{{some-component name=(concat firstName " " lastName)}}
```

`fmt` example:

```hbs
{{some-component name=(fmt "{0} {1}" firstName lastName)}}
```

This doesn't add anything new product-wise, it's only arguably more readable. Specifically, in my work app I have something like this:

```hbs
{{#let (compute (action "userLabel") field) as |userLabel|}}
  {{some-component
    userLabel=(concat userLabel " (level: " playerLevel ")")
  }}
{{/let}}
```

Which would perhaps be clearer if rewritten as:

```hbs
{{#let (compute (action "userLabel") field) as |userLabel|}}
  {{some-component
    userLabel=(fmt "{0} (level: {1})" userLabel playerLevel)
  }}
{{/let}}
```

Thoughts? It's basically like [elm-string-interpolate](https://github.com/lukewestby/elm-string-interpolate) or C#'s `string.Format`, but for Handlebars. [ember-computed-template-string](https://github.com/intercom/ember-computed-template-string) would be the computed property version of this.

**Comment by vvscode** [comment]
@nucleartide  did you start coding for this proposal? or slot still free ? )

**Comment by nucleartide** [comment]
@vvscode i have not started, just wondering what the dockyard people think :)

**Comment by poteto** [comment]
@nucleartide Thanks for the suggestion, I'd recommend opening a PR on https://github.com/romulomachado/ember-cli-string-helpers as we are in the process of deprecating and removing String helpers from this addon. The goal of `ech` is to become more of a functional library like `ramda` vs a "Swiss army knife" util like lodash, so string helpers don't really help achieve that goal. Hope that makes sense

**Comment by nucleartide** [comment]
Ah that makes sense, I will open a PR there. Closing this issue.
