### ISSUE TITLE
isPromise does not return true for native promises

### ISSUE THREAD

**Issue by Asherlc** [DockYard/ember-composable-helpers#247]
## Version
1.0.0

## Test Case
isPromise(Promise.resolve());

## Steps to reproduce
Not sure there's anything more to this -- maybe misunderstanding?

## Expected Behavior
Return true

## Actual Behavior
Returns false

`#finally` isn't part of the Promise spec, but it's in `RSVP.Promise` and other libraries, so that condition should be removed.

**Comment by poteto** [comment]
`isPromise` is private API for this addon

**Comment by Asherlc** [comment]
@poteto if you use the `pipe` helper with a native Promise-returning action, it won't wait to fire the next action. Maybe I wrote this up wrong?

**Comment by poteto** [comment]
Ah I see, that makes sense now. Yes, in that case would you like to open a PR to remove the `finally` check?

**Comment by Asherlc** [comment]
@poteto sure thing, check out https://github.com/DockYard/ember-composable-helpers/pull/248
