### ISSUE TITLE
[BUG] except option doesn't exclude from addon's tree

### ISSUE THREAD

**Issue by marcemira** [DockYard/ember-composable-helpers#250]
## Version
1.1.3

## Test Case
I already have a `titleize` helper on some other addon (a shared addon between multiple ember apps on our company) I can't rename our helper because it beeing used on many other apps as dependency.

## Steps to reproduce
Try to serve the application

## Expected Behavior
To exclude `titleize` from the Funnel tree

## Actual Behavior
ember serve/build throws the error: 
```
Error: EEXIST: file already exists, symlink '/home/marcemira/projects/company/secret-project/node_modules/ember-composable-helpers/app/helpers/titleize.js' -> '/home/marcemira/projects/company/secret-project/tmp/coffee_script_filter-output_path-OJ87w4vb.tmp/secret-project/helpers/titleize.js'
```

**Comment by martndemus** [comment]
I think I'm just going to wait for module unification to fix this problem.
