### ISSUE TITLE
2.0.0 still trying to bower install packages on Ember 2.11.0

### ISSUE THREAD

**Issue by denchen** [DockYard/ember-composable-helpers#254]
## Version
2.0.0

## Test Case
N/A

## Steps to reproduce
* A repo that's been upgraded to `ember-cli@2.11.0` (and hence has no core Ember packages in `bower.json`)
* However, this repo still has a `bower.json` for some third-party libraries that still need Bower (waiting on these libraries to have 2.11.0 support)
* `% ember install ember-composable-helpers`

## Expected Behavior
Nothing gets added to `bower.json`

## Actual Behavior
`ember-cli-shims` is installed via Bower.

This is the output from `ember install ember-composable-helpers`:

    % ember install ember-composable-helpers
    installing ember-composable-helpers
    install bower package ember-cli-shims
    cached https://github.com/ember-cli/ember-cli-shims.git#0.1.3
    cached https://github.com/components/ember.git#2.11.0
    Installed browser packages via Bower.
    Installed addon package.

*However*, if I remove/rename my `bower.json` first, then I get:

    % ember install ember-composable-helpers
    installing ember-composable-helpers
    install bower package ember-cli-shims
    WARNING: Skipping bower install: bower.json not found
    Installed addon package.

**Comment by RobIsHere** [comment]
This also just happened on a project that started clean with Ember 2.12 and didn't have bower deps at any time.

**Comment by buschtoens** [comment]
[That's why.](https://github.com/DockYard/ember-composable-helpers/blob/00f0078d97dc3700093548384b719dd81f129f76/blueprints/ember-composable-helpers/index.js#L4-L6) I don't know if this is still needed / intended.

**Comment by QuantumInformation** [comment]
I just got a new bower file: (

![image](https://user-images.githubusercontent.com/216566/27083263-e012f12a-503f-11e7-9eb9-be0ea0e5e5d5.png)
