### ISSUE TITLE
Hash helper returns EmptyObject instead of POJO

### ISSUE THREAD

**Issue by thedig** [DockYard/ember-composable-helpers#256]
## Version
2.0.0

## Test Case
https://ember-twiddle.com/72343ae787c42f92c9a3c5cbbeb4b923?openFiles=templates.application.hbs%2C

## Steps to reproduce
Just open the console and see what is logged. `hash` helper outputs an EmptyObject which has no constructor. This breaks on libraries expecting it to behave like a POJO.

## Expected Behavior
hash should create a POJO or some version of Object that has this interface

## Actual Behavior
hash produces an EmptyObject with an undefined constructor

Specifically found this while using `ember-cli-g-maps` which looks to call function `hasOwnProperty` on the object.

Twiddle:
```
{{log "is this hash an empty object?:"}}
{{log (hash content="hello")}}
```

Console:
```
is this hash an empty object?:
ember.debug.js:10351 
EmptyObject
content: "hello"
__proto__: Object
    constructor: undefined
```

**Comment by thedig** [comment]
Finding similarly highlighted concern here - https://www.bountysource.com/issues/40210927-cannot-convert-object-to-primitive-value

If this is by design I'm curious as to why. Otherwise I'll probably need to create my own helper that returns a regular object.

**Comment by martndemus** [comment]
I'm sorry, but the `hash` helper is not included in this addon, the `hash` helper comes from Ember.JS directly.

**Comment by thedig** [comment]
a-ha my confusion then, thanks for clarifying!
