### ISSUE TITLE
group-by does not support integer

### ISSUE THREAD

**Issue by romaef** [DockYard/ember-composable-helpers#262]
I'm trying to group the users by their different groupIDs

```
{{#each-in (group-by "groupID" users) as |groupID users|}}
<h3>{{groupID}}</h3>
<ul>
    {{#each users as |user|}}
        <li>{{user.userID}}</li>
        <li>{{user.name}}</li>
        <li>{{user.address}}</li>
        {{/each}} 
    {{/each}}
</ul>
{{/each-in}}
```

I'm getting an error
ember.debug.js:18015 Assertion Failed: The key provided to get must be a string, you passed 4
Error

**Comment by nselikoff** [comment]
Ran into this issue today. Maybe the helper could coerce ints to strings when grouping?

**Comment by snewcomer** [comment]
This should be a problem anymore!
