### ISSUE TITLE
Optional helper with noop instead of identity result?

### ISSUE THREAD

**Issue by monovertex** [DockYard/ember-composable-helpers#264]
I hit this use case in our app, but the usage of actions in this particular case is not exactly orthodox, because we call the function directly and use its result, instead of using `sendAction`.

I solved this issue by creating a custom helper, similar to the `optional` one included in ember-composable-helpers, but I was wondering if it would make sense as an addition to the library.

I can submit a PR, but I wanted to confirm the usefulness of this idea.

**Comment by snewcomer** [comment]
I think a `call` helper might make sense
