### ISSUE TITLE
Frozen array causes errors with find-by

### ISSUE THREAD

**Issue by ming-codes** [DockYard/ember-composable-helpers#269]
`find-by` and possibly other helpers that wraps using `Ember.A` throws error.

## Version
1.1.2, 2.0.1

## Test Case
https://ember-twiddle.com/e5184a790c517817d6a64650ddb88ea7?openFiles=templates.application.hbs%2C

## Steps to reproduce
https://ember-twiddle.com/e5184a790c517817d6a64650ddb88ea7?openFiles=templates.application.hbs%2C

## Expected Behavior
No error!

## Actual Behavior
Error thrown

**Comment by anehx** [comment]
Happens with `{{includes}}` as well, see https://ember-twiddle.com/94cbfbbea6e38e60d1966b19fbd9dc60
