### ISSUE TITLE
Tree shaking not working in Ember CLI 2.14-beta

### ISSUE THREAD

**Issue by mwpastore** [DockYard/ember-composable-helpers#272]
## Version

2.0.1

## Steps to reproduce

Add this to ember-cli-build.js:

```javascript
module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    // ..

    'ember-composable-helpers': {
      only: [
        'dec',
        'find-by',
        'inc',
        'object-at',
        'sort-by'
      ]
    },

    // ..
```

And ran `ember serve` (or `ember build --environment production`).

## Expected Behavior

In `ember serve`: expected other helpers to not be available.

In `ember build`: expected other helpers to not be present in vendor.js.

**Comment by nightire** [comment]
[this line](https://github.com/DockYard/ember-composable-helpers/blame/master/index.js#L31) causes this issue, after ember-cli v2.13, module's name is resolved without the `modules` prefix, so none of helpers would be considered as a helper.

I think simply remove the line beginning part from the regex should be enough to fix this issue.

**Comment by poteto** [comment]
@mwpastore @nightire can you please give 0b25af617d81ab5fddffed12a937df9ea060ae84 a try? thanks

**Comment by nightire** [comment]
@poteto Unfortunately it does not work 🙀, I might guess it wrong.

**Comment by nightire** [comment]
Confirmed, it's OK now.
