### ISSUE TITLE
Promise-aware compute helper

### ISSUE THREAD

**Issue by rmmmp** [DockYard/ember-composable-helpers#280]
What are your thoughts on making `compute` promise-aware? This would be useful in my apps and I can't be the only one that needs it, right? 😀

**Comment by mwpastore** [comment]
Hi @rmmmp, I have two CP macros that I use for this purpose, and I've made them available in a [gist](https://gist.github.com/mwpastore/34c4c4acfe2814f5265eea4158524b9a) if you're interested. You'll need to install ember-macro-helpers, have ember-cli-babel >= 6.6 (I think), and have object-rest-spread enabled in Babel and ESLint to use them as written. 

You might also consider taking a look at the promise.array and promise.object CP macros in ember-awesome-macros.

**Comment by mwpastore** [comment]
Hi @rmmmp, I've removed my previous comment because it was totally not what you were asking. My apologies. 

Have you taken a look at ember-promise-helpers? If your compute action returns a promise, you could do something like `{{await (compute (action 'xhrSquare') 2)}}`.

**Comment by rmmmp** [comment]
@mwpastore Yup I've seen ember-promise-helpers but didn't come across to me that I could do that. Though I wouldn't like to do that anyway since it'll make my payload bigger if I install that addon only for the `await` helper (no tree-shaking).

Anyway, I've rolled out an internal solution for now so I'm closing this. Feel free to reopen if there are plans to make this promise-aware.

**Comment by mwpastore** [comment]
Yeah, I hear you. I definitely prefer the PromiseProxy approach for a variety of reasons. Glad you were able to work something out.
