### ISSUE TITLE
2.0.3 has deprecations for relying on old shims that are fixed on master

### ISSUE THREAD

**Issue by rondale-sc** [DockYard/ember-composable-helpers#283]
Currently this addon is causing deprecations on `v2.0.3` that have long since been addressed (>5 months ago) on master.  Is there any discussion as to when the next release will be cut?

Cheers! :beers:

**Comment by samselikoff** [comment]
Bump - looks like lots of work has happened since the last version was cut.

Need some help with the release?

**Comment by snewcomer** [comment]
Onto 4.0.  Let us know if there is still a problem!
