### ISSUE TITLE
[FEATURE REQUEST] {{#with}} multiple Args

### ISSUE THREAD

**Issue by Techn1x** [DockYard/ember-composable-helpers#284]
Proposal;
```handlebars
{{#with someobj.a someobj.b as |c d|}}
  ...
{{/with}}
```

The same functionality as the current Ember `with`  template helper, but this will allow for multiple args to be provided, resulting in cleaner code for when multiple properties need to be aliased.

Current `with` template helper would need the following code to perform the same as above
https://emberjs.com/api/ember/2.17/classes/Ember.Templates.helpers/methods/with?anchor=with
```handlebars
{{#with someobj.a as |c|}}
  {{#with someobj.b as |d|}}
    ...
  {{/with}}
{{/with}}
```

I'm not sure if you can override the existing `with`  template helper or if it will need a new name. But theoretically if you do override it, the functionality will remain the same and it shouldn't break anything for existing `with` implementations.

**Comment by Techn1x** [comment]
(If this is something that is better suited for Ember to support out of the box rather than here in this addon, let me know and I'll go request it over there)

**Comment by buschtoens** [comment]
You might be interested in [`ember-let`](https://github.com/thefrontside/ember-let), which does exactly that.

IIRC the `{{with}}` helper already implicitly supports passing multiple arguments, however that is not explicitly documented and should be treated as public API. The major difference between `{{let}}` and `{{with}}` is, that the latter implicitly checks the (first) arg for truthyness.

**Comment by Techn1x** [comment]
I did actually try the `{{with}}` template helper with multiple args but it errored saying that multiple args not supported

However ember-let sounds perfect, I'll give it a go! Thanks

**Comment by buschtoens** [comment]
> I did actually try the {{with}} template helper with multiple args but it errored saying that multiple args not supported

Then this was changed recently, presumably with 2.17. I just recently had a chat about that with rwjblue. :slightly_smiling_face: 

Glad I could help you.
