### ISSUE TITLE
sort-by helper broken in ember 2.18

### ISSUE THREAD

**Issue by BryanCrotaz** [DockYard/ember-composable-helpers#289]
sort-by helper in an each block returns no DOM.

```
{{#each model as |one|}}
  {{one.name}}<br/>
{{/each}}

name1
name2
name3
```

```
{{#each (sort-by "name" model) as |one|}}
  {{one.name}}<br/>
{{/each}}

<!-- No DOM rendered -->
```

This was working in Ember 2.14

**Comment by ryanlabouve** [comment]
I tried to create this bug and could not. 

Unfortunately when I tried to do this in a twiddle I could not get Ember 2.18.1 and the latest `ember-composable-helpers` to install, so I just made a quick repo: https://github.com/ryanlabouve/ember-composable-helpers-289

Here's the commit where I recreate your example above with a simple object: https://github.com/ryanlabouve/ember-composable-helpers-289/commit/767c4e02b0d68908097e689befcdcb8f60f8eff3

And here's where I try to create your example above with a `PromiseArray`, which I'm assuming is what your model is: https://github.com/ryanlabouve/ember-composable-helpers-289/commit/7ab15ca38fe31a3ec7447c26bcbc93c7fcca8a0b

**Comment by rwwagner90** [comment]
I'm also seeing this not work

**Comment by snewcomer** [comment]
https://github.com/DockYard/ember-composable-helpers/issues/318#issuecomment-497635938
