### ISSUE TITLE
[FEATURE REQUEST] Add 'sort' helper

### ISSUE THREAD

**Issue by Techn1x** [DockYard/ember-composable-helpers#297]
Currently, we have a `sort-by` helper which allows you to provide an array (of objects/hashes) and a sortkey or sort function.

I've found myself with an array of strings that I want to sort alphabetically in the template, and it seems I can't do that with the sort-by helper, because it expects an array of objects or hashes

Ideally, I could do this
```javascript
unsortedFruitsArray: ['apple','carrot','banana']
```
```handlebars
{{display-fruits fruits=(sort unsortedFruitsArray desc=true)}}
```

And then the component would apply the `Array.prototype.sort()` function (with a standard compare function, because javascripts default sort() is dumb) to the passed array, which should work for arrays of basic integers and strings.

**Comment by vvscode** [comment]
https://github.com/DockYard/ember-composable-helpers#sort-by

**Comment by vvscode** [comment]
I believe that such kind of sorting should be done out of template

**Comment by Techn1x** [comment]
Happy for this to be closed if that's the case :)

**Comment by oskarrough** [comment]
@Techn1x have you seen https://github.com/DockYard/ember-composable-helpers/pull/281?

**Comment by Techn1x** [comment]
No I hadn't, thanks that exactly what I was after. I do think it would be useful to be merged in, but that PR has been sitting there a while..
