### ISSUE TITLE
[FEATURE REQUEST] Add 'includes' helper for checking substring in a string

### ISSUE THREAD

**Issue by aandis** [DockYard/ember-composable-helpers#298]
A `includes` helper for checking whether a [string contains a substring](https://stackoverflow.com/questions/1789945/how-to-check-whether-a-string-contains-a-substring-in-javascript) could be handy.
Example -

```handlebars
{{#if (includes "apples" "apples and oranges")}}
  Apple and Orange!
{{/if}}
```

I was hoping the `contains` helper does this but looks like it only works on arrays.

**Comment by betocantu93** [comment]
+1

**Comment by Techn1x** [comment]
This might go into the ember-cli-string-helpers project perhaps?

**Comment by Frozenfire92** [comment]
Great feature request, but I agree it being more suited to https://github.com/romulomachado/ember-cli-string-helpers

**Comment by snewcomer** [comment]
Great!  Looks like a great PR!  Closing for now...
