### ISSUE TITLE
Bower dependancies installed in new ember app

### ISSUE THREAD

**Issue by evoactivity** [DockYard/ember-composable-helpers#303]
## Version
2.1.0

## Steps to reproduce
1) Create fresh ember 3.5 app
2) `ember install ember-composable-helpers`

## Expected Behavior
ECH is installed with no bower dependancies

## Actual Behavior
ECH is installed with `ember-cli-shims` as a bower dependancy, I also end up with ember 2.18.2 and jquery 3.3.1 added to the project as bower dependancies.

**Comment by lougreenwood** [comment]
I'm also seeing this :(

**Comment by balinterdi** [comment]
I just submitted #304 that would fix this.

**Comment by wukongrita** [comment]
May I know how can I install with the latest commit? while waiting for the new release...

**Comment by balinterdi** [comment]
Instead of putting a version number in `package.json` for the package, put the Github path in:

```js
// package.json
{
  devDependencies: {
    "ember-composable-helpers": "DockYard/ember-composable-helpers"
  }
}
```

You then do `yarn` (or `npm install`) to install the package and you're off to the races.
