### ISSUE TITLE
`only` and `except` leave broken module references and unnecessary code in app tree

### ISSUE THREAD

**Issue by ef4** [DockYard/ember-composable-helpers#308]
The `only` and `except` options remove the implementations of unused helpers from the *addon* tree, but they don't remove the corresponding reexport modules from the *app* tree.

This leaves unnecessary and broken modules in the resulting application.

The same problem exists in the `addon/index.js` file, which will try to import every helper regardless of whether it has been stripped out. This makes it impossible to import the remaining helpers via that module.

(I noticed because this breaks [embroider](https://github.com/embroider-build/embroider) and will break any system that tries to verify imports at build time.)

**Comment by snewcomer** [comment]
@ef4 👋 I'm coming in naive, but is this to say this feature has always been broken?  Is it possible to remedy?  

Lastly, can you expand on this?  Are you saying the whole process of filtering out modules will "always" break embroider?
> to verify imports at build time.

**Comment by ef4** [comment]
Yes, I think has always been broken. I mean, it succeeds in dropping the implementation of unused helpers from the app. But it leaves behind dangling references that still refer to the removed code.

> Are you saying the whole process of filtering out modules will "always" break embroider?

No, embroider can handle addons that have custom broccoli shenanigans like this. The thing it's unhappy about is that the addon is emitting imports that point at nonexistent files. Dropping the files is fine, but that should also involve dropping the imports that refer to those files.

I now have [a compatibility adapter](https://github.com/embroider-build/embroider/blob/b45634c511b8cd717dbdaa7e42c3eaa8b3fd99f5/packages/compat/src/compat-adapters/ember-composable-helpers.ts) in embroider specifically to patch over this issue in ember-composable-helpers. The things it's doing (removing the files from the app tree that don't have corresponding files in the addon tree, and rewriting the index.js file to remove imports of missing files) may be useful to move directly into ember-composable-helpers instead.

**Comment by snewcomer** [comment]
@ef4 What if we used embroider as its build system?  Would you recommend that?  Looks like v1 format is applicable if we did?

**Comment by ef4** [comment]
No, in order to use embroider to drop the unused helpers embroider needs to be able to see the entire app. It's not something a single addon can opt into.
