### ISSUE TITLE
map by not functional?

### ISSUE THREAD

**Issue by snewcomer** [DockYard/ember-composable-helpers#315]
I'm noticing that map-by may be modifying the content passed to it.  Still need to verify, but just putting this issue here so I don't forget to write some tests to verify/disprove what I was seeing

**Comment by GavinJoyce** [comment]
@snewcomer perhaps this can be closed? if not, perhaps you could add a failing test?

**Comment by snewcomer** [comment]
Yes, I think I understand my own mistake now.  THanks for the reminder!
