### ISSUE TITLE
`sort-by` doesn't seem to work with the latest Octane blueprint

### ISSUE THREAD

**Issue by GavinJoyce** [DockYard/ember-composable-helpers#318]
The following template shows [`sort-by`](https://github.com/DockYard/ember-composable-helpers/blob/master/addon/helpers/sort-by.js) working in Ember `3.9.1` and `3.10.0-beta.5` but not in an app using the latest Octane blueprint (`ember new octane-app -b @ember/octane-app-blueprint`):

**application.hbs**
```hbs
{{#let (array (hash age=1) (hash age=5) (hash age=2)) as |rows|}}
  <h4>Raw Rows:</h4>
  {{#each rows as |row|}}
    [row: {{row.age}}]
  {{/each}}

  <hr>

  <h4>Sorted Rows:</h4>
  {{#each (sort-by "age" rows) as |row|}}
    [sorted: {{row.age}}]
  {{/each}}
{{/let}}
```

<img width="287" alt="Screen Shot 2019-05-02 at 09 42 22" src="https://user-images.githubusercontent.com/2526/57064576-9de30e00-6cbe-11e9-97f0-8cbbe035174e.png">

<img width="244" alt="Screen Shot 2019-05-02 at 09 35 55" src="https://user-images.githubusercontent.com/2526/57064313-d0403b80-6cbd-11e9-9af0-4c201cc55b69.png">

~~possibly related to https://github.com/DockYard/ember-composable-helpers/issues/289~~

**Comment by GavinJoyce** [comment]
If I add some logging, there's a difference in timing:

<img width="610" alt="Screen Shot 2019-05-02 at 09 46 44" src="https://user-images.githubusercontent.com/2526/57064840-7b9dc000-6cbf-11e9-8cc1-c37a4abc043c.png">

<img width="505" alt="Screen Shot 2019-05-02 at 09 47 16" src="https://user-images.githubusercontent.com/2526/57064809-63c63c00-6cbf-11e9-81ec-f3ddabcf3102.png">

**Comment by GavinJoyce** [comment]
It seems that in Octane, we skip `notifyObservers` within `notifyPropertyChange`:

Octane:

<img width="780" alt="Screen Shot 2019-05-02 at 10 08 48" src="https://user-images.githubusercontent.com/2526/57065798-7130f580-6cc2-11e9-8672-dc1c9ecb8a37.png">

Ember 3.9:

<img width="636" alt="Screen Shot 2019-05-02 at 10 08 10" src="https://user-images.githubusercontent.com/2526/57065811-75f5a980-6cc2-11e9-8715-f940a34ba35c.png">

**Comment by GavinJoyce** [comment]
It looks like a change was made to make observes asynchronous:

https://github.com/emberjs/ember.js/commit/405d42388472c30e3d7d98c59a000b7ebe4a37c0

```
Observers have been made asynchronous. They now flush during specific
  phases of the runloop - just before render, and potentially after
  render if anything was scheduled (this will begin a new runloop).
  They poll now to check if any changes occured, rather than firing
  synchronously when the change occurs, which is how we made them work
  entirely using tags without chains. Observers inherited from
  EmberObject classes begin polling at the same time as
  `finalizeChains`.
```

**Comment by GavinJoyce** [comment]
I wonder if we can move away from using observers and computed properties?

**Comment by snewcomer** [comment]
👋 Gavin.  My understanding of your proposal would be to remove observers where initial computation could be done in `compute`.  And then keep observers for `recompute`?  On initial look, it seems good to me!

**Comment by GavinJoyce** [comment]
@snewcomer thanks, yours is a better and more nuanced proposal than my original "don't use observers". I believe that your strategy is a good one and should allow us to release a version of `ember-composable-helpers` which works for both Ember 3.9 and Octane

**Comment by GavinJoyce** [comment]
The challenge here appears to be that in Octane the `contentDidChange` observer fires after the helper computes, which results in an infinite render when rendered for the first time.

```js
contentDidChange: observer('content', function() {
  this.recompute();
})
```

**Comment by snewcomer** [comment]
So it seems either a bug in Ember, helper's 'compute' is executed when content changes or there may be a new construct we can take advantage?  Would be ok with releasing a major version for octane and keeping minor/patch work for pre-octane if need be.  What do you think?

**Comment by buschtoens** [comment]
Ran into the exact same problem for `filter-by` btw, as it also uses an observer.

**Comment by buschtoens** [comment]
I'll repeat my findings from #319 here to keep this issue streamlined:

Besides potentially causing infinite loops (as @GavinJoyce found out), `contentDidChange` only gets executed in the _next_ runloop. This means that values inside a template van get out of sync for the duration of one runloop.

```hbs
{{loggy-mc-logface
  filterProperty=this.filterProperty
  filteredItems=(filter-by this.filterProperty this.items)
}}
```

```ts
import { helper } from '@ember/component/helper';

export function loggyMcLogface(positional, named) {
  console.log(named);
}

export default helper(formatCurrency);
```

When `filterProperty` updates, `loggy-mc-logface` will re-compute twice:

1. With the new `filterProperty`, but stale `filteredItems`.
2. Then with the new `filterProperty` and new `filteredItems`.

**Comment by buschtoens** [comment]
@pzuraq https://github.com/emberjs/ember.js/pull/17951#issuecomment-488745786:

> Unfortunately, this is the only way we could make observers interop with tracked properties, since they're fundamentally lazy, so if we this is too problematic and we do have to revert it, it means we'll also have to drop that interop 😕

I have my fingers crossed, that we _don't_ have to drop it. 🤞
However, this means we somehow have to get rid of observes _completely_ in this addon.

**Comment by buschtoens** [comment]
I think we cannot solve this problem with the current Ember `Helper` API. `Helper` _itself_ only calls `compute` when the input parameters actually change identity, e.g. `array.pushObject(1)` is ignored.

Whereas native Glimmer helpers recompute whenever their input tags are dirty, which might not necessarily mean that the value _actually did_ change, but that it _could_ have changed. AFAIK this is also true for array mutations (how else would `{{#each}}` work?), which is effectively what we need.

Assuming that observers will stay async, I think this library would have to be rewritten as native Glimmer helpers. Is it even possible yet for an Ember addon to provide Glimmer helpers?

Is my assessment incorrect?

**Comment by GavinJoyce** [comment]
Posting here for anyone who didn't see this on the `#st-octane` discord channel:

<img width="659" alt="Screen Shot 2019-05-09 at 21 33 43" src="https://user-images.githubusercontent.com/2526/57485454-a67daa80-72a3-11e9-8800-0b87c59f6fbc.png">

Hopefully this means that we won't have to change anything in `ember-composable-helpers` for Octane

**Comment by GavinJoyce** [comment]
I've confirmed that this has been fixed with https://github.com/emberjs/ember.js/pull/18059, `sort-by` now works with the latest Octane blueprint. 

We'll need to figure out how we can migrate away from observers in future, I believe it should be possible to support both classic and tracked properties for a time, we'd only need to install the observer for the classic arguments. I've commented on the RFC: https://github.com/emberjs/rfcs/pull/494#issuecomment-497603878

I'll close this issue as it's no longer valid
