### ISSUE TITLE
Should `append` be renamed to `concat`?

### ISSUE THREAD

**Issue by GavinJoyce** [DockYard/ember-composable-helpers#326]
While working on [upgrading to Octane](https://github.com/DockYard/ember-composable-helpers/pull/321), I refactored the `append` helper into:

```js
import { helper } from '@ember/component/helper';

export function append([...arrays]) {
  return [].concat(...arrays);
}

export default helper(append);
```

Perhaps we should deprecate `append` and rename to `concat`?

**Comment by buschtoens** [comment]
There's already the built-in [`{{concat}}`](https://api.emberjs.com/ember/3.11/classes/Ember.Templates.helpers/methods/concat?anchor=concat) for concatenating strings.

**Comment by GavinJoyce** [comment]
ah yes, thanks
