### ISSUE TITLE
Refactor `sort-by` helper

### ISSUE THREAD

**Issue by GavinJoyce** [DockYard/ember-composable-helpers#327]
This is a follow on task from https://github.com/DockYard/ember-composable-helpers/pull/321

We should rebuild [`sort-by`](https://github.com/DockYard/ember-composable-helpers/blob/3276a2217a970da69b6901be2e1f867071dd7aba/addon/helpers/sort-by.js) to be a functional helper, like all the others. I didn't convert it in https://github.com/DockYard/ember-composable-helpers/pull/321 as it doesn't use observers (removing observers was my main aim with the PR) and it's a little more challenging than the other helpers

**Comment by iamareebjamal** [comment]
Hi, sortBy is not working with Ember Octane/angle bracket syntax. Is this issue related?
