### ISSUE TITLE
Teardown observers in the willDestroy hook

### ISSUE THREAD

**Issue by poteto** [DockYard/ember-composable-helpers#33]

**Comment by martndemus** [comment]
Is this needed? Won't the observers be torn down when the helper is torn down?

**Comment by poteto** [comment]
According to @rwjblue no, we basically always have to teardown observers
explicitly
On Sun, Feb 21, 2016 at 7:52 AM Marten <notifications@github.com> wrote:

> Is this needed? Won't the observers be torn down when the helper is torn
> down?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DockYard/ember-functional-helpers/issues/33#issuecomment-186818541>
> .
>
-- 
Lauren Tan
Senior Developer

Visit us: http://dockyard.com
Call us: (855) DOCK-YRD
Follow me on Twitter: https://twitter.com/sugarpirate_
Follow us on Twitter: https://twitter.com/DockYard

**Comment by martndemus** [comment]
I have never heard of having to tear down observers, are you sure you are not confusing observers with event handlers?

AFAIK you only have to teardown observers added via `addObserver`.

**Comment by rwjblue** [comment]
You definitely need to tear down when using `addObserver`, but we are using `Ember.defineProperty`, they _might_ be torn down when the object is destroyed, but I'm unsure.  We should test...

**Comment by martndemus** [comment]
With my simple test it looks like you don't have to: https://ember-twiddle.com/df5a05822ec6fd8405bb

**Comment by poteto** [comment]
OK, closing for now.
