### ISSUE TITLE
map-by not working with 3.16

### ISSUE THREAD

**Issue by RachelEversmann** [DockYard/ember-composable-helpers#349]
## Version
    "ember-composable-helpers": "^3.1.1",
    "ember-cli": "~3.16.0",

## Test Code
```html
{{#each (map-by 'name'  this.users) as |user|}}
   <div>{{user}}</div>
{{else}}
   <div>array is empty</div>
{{/each}}
```

with

```javascript
import Component from '@glimmer/component';

export default class extends Component {
   users = [ { name: 'Bob' }, { name: 'Sally } ];
}
```

## Expected Behavior

`
   Bob
   Sally
`

## Actual Behavior
`
   array is empty
`

**Comment by RachelEversmann** [comment]
Similar problems with map-by, filter-by, and union

**Comment by snewcomer** [comment]
@RachelEversmann I just tested on a sample app and am not seeing any issues.  Do you think you could provide an example repo?  Also happen to have info on the Node version?

Side note, but I don't think it is the issue - I noticed in your example `'Sally` was missing an end quote.

**Comment by snewcomer** [comment]
https://github.com/emberjs/ember.js/issues/18750

Looks to be a bug if it was an ArrayProxy!  I'm assuming it may be.

**Comment by RachelEversmann** [comment]
Looks like it was a bug with Ember Source and they fixed it. This is not a problem now.

**Comment by Shajansheriff** [comment]
@RachelEversmann @snewcomer  is it working? I am still facing the same problem in ember-cli 3.17.

**Comment by Shajansheriff** [comment]
```{{#each-in this.listItems as |label items|}}
    {{#with (find-by 'label' label items) as |labelObj|}}
{{labelObj.name}}
{{/with}}
{{/each-in}}```

find-by is not working as expected in the scenario. Values are in same prototype & it exist. I think we have problem with find-by helper. @RachelEversmann @snewcomer
