### ISSUE TITLE
[FEATURE REQUEST] Object helpers: keys, values, entries, and fromEntries helpers

### ISSUE THREAD

**Issue by gabrielgrant** [DockYard/ember-composable-helpers#351]
Ember allows iterating over keys and values in an object using `{{each-in}}`, but processing those Object entries using the many array helpers (or even, for instance, getting the number of entries in an object) is currently not possible without writing a computed prop/getter to pluck off the keys, values, or entries.

Would there be interest in a PR that adds the basic Object -> array static methods as additional Object helpers?

Specifically:

`{{keys someObj}}` --> `Object.values(someObj)`
`{{values someObj}}` --> `Object.values(someObj)`
`{{entries someObj}}` --> `Object.entries(someObj)`
`{{from-entries someObj}}` --> `Object.fromEntries(someObj)`

Specific use-cases:

1. I have an array of records with sorted by category (possibly from use of `{{group-by}}`). I only want to display a category heading and/or anchor link if there is more than one category after grouping.

`{{#if (gt (keys byCategory).length 1)}}...`

2. I want to use the items in my object in a specifc order (that is not the default of insertion order). Eg to alphabetize by key:

`{{#each (sort-by 0 (entries myObj)) ...`

**Comment by snewcomer** [comment]
@gabrielgrant I like the idea!  Would gladly accept a PR if you have time.

**Comment by Shajansheriff** [comment]
@snewcomer working on it. 😄 You can expect a PR very soon

**Comment by snewcomer** [comment]
Thanks for the PR!  Is this ok to close?

**Comment by gabrielgrant** [comment]
thanks for doing the leg-work @Shajansheriff and for getting it in, @snewcomer 

Noticed that only the `keys` and `entries` helpers made it in. These are probably the two more useful ones, but I had a need for the other two too (for combining search terms from multiple fields, and generating query params, respectively), so just opened [a PR](#359 ) with `values` and `from-entries` as well

**Comment by snewcomer** [comment]
Thanks a lot for the PR(s)!  3.2.0 released!
