### ISSUE TITLE
[FEATURE REQUEST] pluck

### ISSUE THREAD

**Issue by mum-never-proud** [DockYard/ember-composable-helpers#354]
I was in need of `pluck` where I can get only the required attribute from an array or array of, objects dot notation is also supported 

eg.

`{{pluck items "data.title"}}` would yield `["aa", "bb", "cc"]`

I have changes in my local forked repo, can raise a pr if needed:)

thanks!

**Comment by snewcomer** [comment]
This seems helpful!  This probably could stay in userland if you don't mind.  Is it basically `Ember.get` with a nested path?  Or is it more complicated?

**Comment by mum-never-proud** [comment]
yea it's basically `Ember.get` filtering undefined & null values which I thought might be useful to feed direct responses instead of applying filter manually

your thoughts @snewcomer ?

**Comment by snewcomer** [comment]
I undoubtedly like your idea!  And we can prune helpers you aren't using to reduce vendor size.  However, since we have the `{{get}}` helper, it solves a good chunk of use cases others may encounter.  Thanks for the issue!
