### ISSUE TITLE
Array helpers are not working after upgrading to 3.17

### ISSUE THREAD

**Issue by Shajansheriff** [DockYard/ember-composable-helpers#356]
## Actual Behavior

Array helpers such as filter-by are suddenly not working in `ember-cli: 3.17.0` . It was working before in 3.14.

**Comment by codebruder** [comment]
Also not running on ember-cli 3.16.1 with ember-composable-helpers v3.1.1

**Comment by Shajansheriff** [comment]
@snewcomer Any update on this?

**Comment by nicomihalich** [comment]
I ran into this recently and it might be an issue with competing versions in your app.  Check in your `package-lock.json` or `yarn.lock` to see if you have an older ([pre-octane](https://github.com/DockYard/ember-composable-helpers/pull/321)) version of `ember-composable-helpers` getting resolved from another dependency.

See [this twiddle](https://ember-twiddle.com/be29436a145837d57d14e2e969d3e7d1) for a working demo of array helpers on`ember` v3.17.0 and `ember-composable-helpers` v3.1.1 so it should work if nothing else is interfering.

**Comment by roberkules** [comment]
having the same issue using `ember-light-table@2.0.0-beta.5` which depends on `ember-composable-helpers@2.4.0`

the only workaround I found so far is replacing the dependency in `package-lock.json`

(guess another workaround would be switching to yarn using _resolutions_)

**Comment by snewcomer** [comment]
https://github.com/emberjs/ember.js/issues/18750
https://github.com/emberjs/ember.js/pull/18770
https://github.com/emberjs/ember.js/pull/18703

I'm guessing ya'll have tried with 3.17 that includes the changes above.  I have seen issues with `ArrayProxy` via ember-data objects...

**Comment by dbollinger** [comment]
Also ran into this, it was an issue with an outdated version of ember-cli-addon-docs I was using declaring a dependency on an older version of this addon.

**Comment by snewcomer** [comment]
I think it might be safe to assume this is a dependency dup problem.  FYI `4.0.0` released!  Also ref #361.  Looks like all tests are passing on 3.17.  

Let me know if you feel like I missed something!
