### ISSUE TITLE
Using undefined arrays with array helpers results in exception @3.x and @4.x, but was working in 2.4

### ISSUE THREAD

**Issue by roberkules** [DockYard/ember-composable-helpers#364]
## Version
3.x and 4.x

## Test Case
version | status | ember-twiddle
------- | ------ | -------------
2.4.0 | working | https://ember-twiddle.com/50396ad6e489d231abbbd18c4877fc73?openFiles=templates.application%5C.hbs%2C
4.0.0 | failing | https://ember-twiddle.com/9aa2bc40db05617dd5133be13f00da22?openFiles=templates.application%5C.hbs%2C

## Steps to reproduce
use a array helper (I used `map`) with an undefined array

## Expected Behavior
array helpers invoked with undefined array should return empty array, as in version 2.x (or it should be marked as breaking change)

## Actual Behavior
`Uncaught TypeError: Cannot read property 'map' of undefined`

---

before `v3.x` ember-composable-helpers used computed macros:

### 2.4.0

```javascript
import { map } from '@ember/object/computed';
// ...
defineProperty(this, 'content', map('array', callback));
```

### 3.x / 4.x

```javascript
return array.map(callback);
```

**Comment by snewcomer** [comment]
@roberkules We would gladly accept a PR!
