### ISSUE TITLE
Rename contains helper to includes

### ISSUE THREAD

**Issue by jelhan** [DockYard/ember-composable-helpers#365]
The naming of `{{contains}}` helper is not intuitive as it does not map the name of the native JavaScript method: `Array.includes()`. It should be renamed to `{{includes}}`. The old name should be deprecated.

Naming it *includes* instead of *contains* [was already considered before implementation](https://github.com/DockYard/ember-composable-helpers/issues/13#issuecomment-186334552) back in 2016 for the same reason. It's not documented why Lauren decided to go with *contains*. It might have been named after `contains` method of `Ember.Array` and `Ember.Enumerable`. That ones [have been deprecated](https://deprecations.emberjs.com/v2.x/#toc_ember-runtime-enumerable-contains) and removed in 2.x.

**Comment by snewcomer** [comment]
Agreed!  PR welcome
