### ISSUE TITLE
Feature - Helper `{{object-pick}}` (equivalent of Lodash.pick)

### ISSUE THREAD

**Issue by MrChocolatine** [DockYard/ember-composable-helpers#382]
### Context

It is usually recommended to only pass the necessary information, wether we are talking about calling functions, components etc.

When dealing with objects I regularly need to to pass subsets of them to my components.

### Solution

In the same vein of [`lodash.pick`](https://lodash.com/docs/4.17.15#pick), I want to propose a new helper `{{object-pick}}` (since `{{pick}}` is already used).

Here is an example of how it would be used:

**Controller**
```js
export class ... {
  myData = {
    id: 123,
    title: 'some title',
    type: 'some-type',
  };
}
```

**Controller's template**
```hbs
<MyComponent @model={{object-pick this.myData "id" "title"}} />
```

**Component**
```js
this.args.model === {
  id: 123,
  title: 'some-title',
};
```

I know the same could be done using the `{{hash}}` helper, but it requires more code and to repeat ourselves:

```hbs
<MyComponent @model={{hash
  id=this.myData.id
  title=this.myData.title
}} />
```

### Notes

The helper [`{{pick}}` already exists](https://github.com/DockYard/ember-composable-helpers#pick) but I would either rename it and keep `{{pick}}` for the new helper I am suggesting (my preferred option), or find another name for this new helper, maybe something like `{{deconstruct}}` ?

**Comment by snewcomer** [comment]
@MrChocolatine Thank you for the issue.  Given we have an easy escape hatch with `hash` (albeit with minor tradeoffs), we should consider using that.
