### ISSUE TITLE
Improve readme with examples where the handlebars helpers can be more powerful than regular CPs

### ISSUE THREAD

**Issue by martndemus** [DockYard/ember-composable-helpers#39]
For example the map by helper

`{{map-by array selectedProperty}}`

is way easier to grok then:

```js
selectedPropertyDidChange: observer('selectedProperty', function() {
  defineProperty(this, 'myMappedArray', mapBy('array', get(this, 'selectedProperty')));
});
```

**Comment by poteto** [comment]
Confirm but I think the example is a bit contrived. You would likely use a computed macro for a `mapBy`:

```js
names: computed.mapBy('users', 'fullName')
```

Maybe an example where you have to use a number of intermediate macro steps to get to the desired result would be better.

**Comment by martndemus** [comment]
I don't think that my example is too contrived, I have done something like that a few times in previous projects. I think both mine and your composition examples are valid examples.
