### ISSUE TITLE
Wrong sorting by multiple values while some values are null

### ISSUE THREAD

**Issue by yrakova** [DockYard/ember-composable-helpers#391]
## Version

4.4.0

see [Pull Request](https://github.com/DockYard/ember-composable-helpers/pull/390)

## Test Case

```
test('it sorts asc by a few params some of those are all null', async function(assert) {
    this.set('array', [
      { creationDate: null, attrs: { trialNumber: '00-01'}, localOrder: 1 },
      { creationDate: null, attrs: { trialNumber: '00-02'}, localOrder: 2 },      
    ]);

    await render(hbs`
      {{~#each (sort-by 'creationDate:asc' 'attrs.trialNumber:asc' 'localOrder' array) as |trial|~}}
        {{~trial.attrs.trialNumber~}}
      {{~/each~}}
    `);

    assert.equal(find('*').textContent.trim(), '00-0100-02');
  })

```
## Steps to reproduce

Try to sort by more than one attributes, where two or more values are null or undefined

## Expected Behavior

Null attributes should be considered equal, and sorting should be continued with the next attribute.

## Actual Behavior

Sorting is applied in the wrong way within nullable attributes (createdDate) and not applied to the next attribute (attrs.trialNumber) at all

**Comment by lifeart** [comment]
@yrakova looks like this issue could be closed
