### ISSUE TITLE
When installed as a production dependency, all helpers are included in the build

### ISSUE THREAD

**Issue by MrChocolatine** [DockYard/ember-composable-helpers#407]
## Version

Version 4.4.1

## Steps to reproduce

- Generate a fresh Ember add-on in version 3.16.2 or 3.26.0
- `yarn install`
- Install the add-on as production dependency `ember install ember-composable-helpers --save`
- Configure the add-on to only include the helper `includes` (or any other helper)

```js
// File `/ember-cli-build.js`

let app = new EmberAddon(defaults, {
  'ember-composable-helpers': {
    only: ['includes']
  },
});
```

- Start dummy app with `ember serve`

## Expected Behavior

The file `/dist/assets/dummy.js` should only contain what is necessary for the helper `includes`.

## Actual Behavior

The file `/dist/assets/dummy.js` contains all the helpers from the add-on `ember-composable-helpers`.

There are 48 occurrences of `ember-composable-helpers` in the file.

Note: when the add-on is installed as a development dependency, the `only` configuration is honoured, 1 occurence of `ember-composable-helpers` in the file `/dist/assets/dummy.js`.

**Comment by snewcomer** [comment]
Hi @MrChocolatine!  I just tried on a fresh project (3.24 && 3.26) and couldn't reproduce.

<img width="1283" alt="Screen Shot 2021-05-01 at 8 01 30 AM" src="https://user-images.githubusercontent.com/7374640/116783272-795bd100-aa53-11eb-8034-603e9deb8645.png">

**Comment by MrChocolatine** [comment]
@snewcomer here is a test repository of the steps described in my initial post:
https://github.com/MrChocolatine/ember-composable-helpers-test-build

Maybe I am doing something wrong or maybe my knowledge of how this is supposed to work is wrong.

**Comment by snewcomer** [comment]
Oh oh I see what is going on.  In an addon (your example repo), it is including them all.  However, when the addon is included in an app, the helpers will be removed I imagine.

**Comment by MrChocolatine** [comment]
@snewcomer I investigated a bit more, this time I created a new application with an in-repo-addon, where this add-on has `ember-composable-helpers` as a production dependency.

https://github.com/MrChocolatine/ember-composable-helpers-test-build_app-with-in-repo

I hope it is not too confusing, I tried to keep things shorts, 2 commits are only important as described in the `README`.

Again, my knowledge might be wrong so please excuse me in advance, but it turns out what we can read here and there... Does not seem correct... ?
