### ISSUE TITLE
transfer maintainers?

### ISSUE THREAD

**Issue by NullVoxPopuli** [DockYard/ember-composable-helpers#451]
I'd like to request this library be transferred away from dockyard on both GitHub and npm.

It's been 1 month since my last issue: https://github.com/DockYard/ember-composable-helpers/issues/450
And since members of Dockyard no longer participates in the ember community, i'd like to help relieve ya'll of duty.

Transferring would help the ember ecosystem continue to move forward and make apps faster (because of plans i have with v2 addons)

We have a few options:
- per [adopted addons program guidelines](https://github.com/adopted-ember-addons/program-guidelines), transferring to me would be the first ntep towards transferring to the many
- i can fork this library
- Dockyard picks up maintenance again

Lemme know what you think!

Thanks!

**Comment by cloke** [comment]
FWIW - we've forked this library, and converted to v2 add-on here. 

https://github.com/crunchybananas/ember-composable-helpers

**Comment by NullVoxPopuli** [comment]
But how do we get all of the ecosystem usage of DockYard's package to use the new thing?

**Comment by cloke** [comment]
I would 100% prefer this to be an adopted add-on, but for our needs we are now using our fork and will continue to develop it in our fork until we can resolve the core issue.
