### ISSUE TITLE
Discuss argument ordering

### ISSUE THREAD

**Issue by martndemus** [DockYard/ember-composable-helpers#54]
```hbs
{{! target object first }}
{{take (sort (filter-by array "active") "lastName" "firstName") 5}}

{{! target object last }}
{{take 5 (sort "lastName" "firstName" (filter-by "active" array))}}
```

Target object last looks like a clear winner to me.

**Comment by poteto** [comment]
One potential point for confusion with target object last might be the discrepancy between the Ember method signature and the helper signature:

```js
computed.mapBy('array', 'prop')
```

vs

```hbs
{{map-by "prop" array}}
```

**Comment by martndemus** [comment]
I think making exceptions to reflect existing Ember API should be considered, but we should not end up with an inconsistent API because of making those exceptions. We should really stick with one option.

**Comment by bcardarella** [comment]
A convention in Elixir is that the "subject" is always the first argument. This creates a contract between functions so that they can always be used with composability in the same way. If you were to take this lesson to heart it would prefer the 2nd version

**Comment by poteto** [comment]
Confirm, the goal for this issue is to decide on the contract moving forward, but to also be aware of the potential downsides. I think if we document the order of arguments clearly in the README we could avoid the confusion between the Ember method and the helper.

**Comment by bcardarella** [comment]
Considering that some functions might only take one argument I think the first argument style would be the easiest to conform to.

WRT readability, the example above `take 5 ...` reads more clearly but I don't think this should be the example to develop this standard around

**Comment by martndemus** [comment]
Good thing to consider: actions are also in the scope of this addon. Actions will greatly benefit from having the subject as last param, because of the currying.

**Comment by brzpegasus** [comment]
I prefer this format:

```hbs
{{take (sort (filter-by array "active") "lastName" "firstName") 5}}
```

Particularly with sorting and filtering, I like to see the collection that is going to be acted upon first, followed by the property names to sort or filter by.

**Comment by flexyford** [comment]
The second option is better for currying, as @martndemus mentioned. 

Looking at `take` from a FP perspective, let's define `take5`, which will return the first 5 items from a list. This makes it more composable in our templates.

```javascript
// js example for clarity
let nums = [1,2,3,4,5,6,7,8,9]
var take5 = take(5) //=> function(list)
take5(nums) //=> [1,2,3,4,5]
```

```hbs
{{!hbs example}}
{{#with (take 5) as |take5|}}
  Active:
  {{take5 (sort (filter-by array "active") "lastName" "firstName")}}
  Inactive:
  {{take5 (sort (filter-by array "inactive") "lastName" "firstName")}}
{{/with}}
```

**Comment by cowboyd** [comment]
I agree with all of the above, Also worth noting that if the helper methods are each individually curried, then it does allow for there to be some flexibility in terms of argument order while still allowing for arbitrary composition. 

That way, if there is a third party library that doesn't necessarily abide by this convention, or if, like in@poteto's `map-by` example above, there might be a overriding concern to.

```hbs
{{take (sort (filter-by array "active") "lastName" "firstName") 5}}
```
is equivalent to
```
{{take _ 5 (sort (filter-by array "active") "lastName" "firstName")}}

**Comment by poteto** [comment]
I'm leaning towards the subject being the last argument, I think my original `mapBy` example can be avoided if we document well.

**Comment by cowboyd** [comment]
@poteto The primary value a currying placeholder provides is the ability to place the same function into a pipe with a different. 

That way, if the value passing through the pipe fits into a different "slot" in that function's api, you don't need to define a new function. Consider the following:

```hbs
{{button {

**Comment by cowboyd** [comment]
@poteto For us, the primary value a currying placeholder provides is the ability to place the same function into a pipe within a different context.

That way, if the value passing through the pipe fits into a different "slot" in that function's api, you don't need to define a new function. Suppose we have a helper called `push` that takes a list, an item and computes a new list containing the item appended to the old list

``` common-lisp
(push items item)
```

In the case of a thing like a shopping cart, you want the free variable to be the item, and the cart is the context:


``` handlebars

<button {{action (pipe (push items) (mut items)) item}}>
  Add Item
</button>
```

But in the case of adding a user to one of potentially many different groups for example, the list is the free variable, and the user is the context:

``` handlebars
<button {{action (pipe (push _ user) (mut administrators)) administrators}}>
  Add User to Administration Team
</button>
```

We've even been experimenting with _always_ using the placeholder within a pipe that curries a function, even when the subject is in the last argument position. That way, the currying is explicitly called out, and you won't miss it coming into the template without context. Here's the original example using that style::

``` handlebars
<button {{action (pipe (push items _) (mut items)) item}}>
   Add Item
</button>
```

In any case, I think it's still very important to have strong conventions around argument ordering, but the ability to curry always gives you that escape hatch should you need it.
