### ISSUE TITLE
Capitalize helper

### ISSUE THREAD

**Issue by poteto** [DockYard/ember-composable-helpers#71]
The helper implementation for `Ember.String.capitalize`:

```hbs
{{capitalize "foo bar baz"}} 
```

**Comment by vikram7** [comment]
Does this helper return "Foo bar baz" or "Foo Bar Baz" or something else?

**Comment by poteto** [comment]
This will essentially be a simple wrapper around `Ember.String.capitalize`, so it will return the same values. You can check the [documentation](http://emberjs.com/api/classes/Ember.String.html#method_capitalize) for more info.

**Comment by poteto** [comment]
Closed in #82
