### ISSUE TITLE
Merge Ember-Curry-Helpers

### ISSUE THREAD

**Issue by flexyford** [DockYard/ember-composable-helpers#73]
I'm really excited to see Ember moving in the direction of declarative templating with `ember-composable-helpers`. I've been working with composing actions and creating explicit handlebars templates with [ember-curry-helpers](https://github.com/flexyford/ember-curry-helpers). This project was based on [ramdJs](http://ramdajs.com/0.19.1/), a functional programming library. I gave an [Ember Meetup Talk](https://www.youtube.com/watch?v=otIpuV9Q4Eg) in January where I built a TODO application with composable curried actions using `ember-curry-helpers`. 

I'm hoping that `ember-composable-helpers` would benefit from some things I've learned from working on `ember-curry-helpers` and consider merging some functionality into this existing repository.

##### Lessons Learned from Ember-Curry-Helpers
- The `pipe` helper passes the return value of the currently evaluated function, as the argument to the next function in the sequence of actions/functions.

- In fact, all functions would benefit from being curried functions. We can then compose more explicit handlebars templates. In the example below, `append` exists as an Ember-Composable-Array-Helper which can accept arguments that are curried-in. The `addToCart` action does not need to exist on the controller anymore.

```hbs
{{!Pipe example with curried function `append`}}
{{!<button {{action (pipe addToCart purchase redirectToThankYouPage) item}}>}}
<button {{action (pipe (append cart) purchase redirectToThankYouPage) item}}>
  1-Click Buy
</button>
```

- `Pipe` is promise aware. In the above example, we would `redirectToThankYouPage` only if `purchase` returns a resolved Promise.

##### Contributing

Rather than duplicate our efforts​, myself and @cowboyd would like to collaborate and merge in this functionality from `ember-curry-helpers` and continue along with with just `ember-composable-actions`.

Of course we'd  be happy to submit a PR for all these things, so let us know if this fits into your vision of `ember-composable-helpers`.

**Comment by poteto** [comment]
I am +1 on this. @cowboyd's post on functional templating + the work done in `ember-curry-helpers` resonates well with the direction I want to take with this addon. I'm not sure if we want to port `ramda.js` to Ember, but I think a good vision to go by is that we want this addon to provide composable primitives for functional templating.

> The pipe helper passes the return value of the currently evaluated function, as the argument to the next function in the sequence of actions/functions.

This addon's `pipe` helper already handles this. 

> Pipe is promise aware. In the above example, we would redirectToThankYouPage only if purchase returns a resolved Promise.

We don't currently have support for promises, but it would be great if we could.

Thoughts @martndemus

**Comment by martndemus** [comment]
Yes please! We would also really appreciate it if you could take a look at #54!

**Comment by flexyford** [comment]
Great, happy to hear that we can combine forces in the direction of this addon! Agreed with @poteto that we do not want to port `ramda.ja` to Ember or Ember-Composable-Helpers. However, it's a good resource for deciding on helper names and currying functionality. When considering a `composable-helper`, changes are it exists in ramda already.

**Comment by cowboyd** [comment]
> This addon's pipe helper already handles this.

So if I'm reading it correctly then, it passes the composed value as the first argument, and then all of the original arguments as subsequent arguments?

**Comment by poteto** [comment]
Ah, I think I misunderstood the original question. We currently only pipe the return value from each function into the next in the sequence, but we don't keep track of the prior values, i.e. we don't actually partially apply or curry. We will need to make updates to the `pipe` helper, sorry I wasn't clear in my first comment.
