### ISSUE TITLE
rename to ember-composable-helpers?

### ISSUE THREAD

**Issue by bcardarella** [DockYard/ember-composable-helpers#8]
There really isn't anything "functional" about the addon. I think "composable" is a better description for the goal.

Discuss...

- [x] Rename in addon
- [x] Deprecate old npm package
- [x] Publish new npm package
- [x] Update Travis and Homu

**Comment by martndemus** [comment]
`ember-handlebars-helpers` would also be an option, although that might be a bit broad.

**Comment by poteto** [comment]
I like `ember-composable-helpers`, I think that communicates the intent more clearly (being able to compose actions and props in hbs)

**Comment by martndemus** [comment]
Renamed!
