### ISSUE TITLE
Would is-even and is-odd helpers be useful?

### ISSUE THREAD

**Issue by vikram7** [DockYard/ember-composable-helpers#94]
For example, `{{is-even num}}` and `{{is-odd num2}}` might be useful occasionally. I can submit a PR if you think these would be helpful.

**Comment by martndemus** [comment]
I feel like those would belong in the `ember-truth-helpers` addon.

**Comment by poteto** [comment]
Agreed.

**Comment by vikram7** [comment]
Makes sense!
